In [1]:
import torch

In [2]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)
result = tensor1 * tensor2
print(result)

tensor([[0.2728, 0.0233, 0.0393],
        [0.0042, 0.3017, 0.1008],
        [0.0365, 0.0140, 0.0449]])


In [3]:
A = torch.rand(5, 3)
B = torch.rand(3)
result = A + B
print(result)

tensor([[0.6899, 0.5055, 1.5591],
        [0.7430, 1.0374, 1.1732],
        [1.0210, 1.0817, 1.2300],
        [0.6136, 0.7811, 0.9995],
        [0.1157, 0.4647, 1.3794]])


In [4]:
tensor1 = torch.rand(4, 3)
tensor2 = torch.rand(3, 2)
result = torch.mm(tensor1, tensor2)
print(result)

tensor([[1.1026, 1.0933],
        [1.1618, 1.2644],
        [0.5303, 0.6588],
        [0.2999, 0.4260]])


In [5]:
tensor = torch.rand(2, 6)
reshaped_tensor = tensor.view(3, 4)
print(reshaped_tensor)

tensor([[0.9845, 0.0762, 0.9303, 0.6446],
        [0.4240, 0.0236, 0.9309, 0.4652],
        [0.6926, 0.5480, 0.6617, 0.3127]])


In [6]:
A = torch.rand(5, 1)
B = torch.rand(5)
result = A * B
print(result)

tensor([[0.0605, 0.0314, 0.1819, 0.1376, 0.1404],
        [0.1161, 0.0603, 0.3493, 0.2643, 0.2696],
        [0.1181, 0.0613, 0.3553, 0.2688, 0.2742],
        [0.0264, 0.0137, 0.0795, 0.0602, 0.0614],
        [0.0577, 0.0299, 0.1735, 0.1313, 0.1339]])


In [7]:
tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(3, 4)
result = torch.mm(tensor1, tensor2.t())
print(result)

tensor([[0.4797, 0.4189, 1.0082],
        [0.6811, 0.2902, 1.0344],
        [0.5305, 0.5108, 1.0733]])


In [8]:
tensor = torch.rand(3, 1)
expanded_tensor = tensor.expand(3, 4)
result_sum = expanded_tensor.sum(dim=1)
print(result_sum)

tensor([3.3652, 0.9750, 2.1061])


In [9]:
tensor = torch.rand(6, 5)
mean_values = tensor.mean(dim=1)
print(mean_values)

tensor([0.5402, 0.4097, 0.5016, 0.4831, 0.6158, 0.5845])


In [10]:
tensor = torch.rand(4, 4)
selected_rows = tensor[[1, 3]]
print(selected_rows)

tensor([[0.7096, 0.0086, 0.0353, 0.0973],
        [0.1835, 0.2806, 0.6362, 0.3894]])


In [11]:
tensor1 = torch.rand(5)
tensor2 = torch.rand(3)
result = torch.ger(tensor1, tensor2)
print(result)

tensor([[0.3740, 0.3360, 0.0878],
        [0.4223, 0.3794, 0.0991],
        [0.5159, 0.4635, 0.1211],
        [0.2798, 0.2514, 0.0657],
        [0.2978, 0.2675, 0.0699]])
