In [ ]:
import numpy as np

1. You have a 2D array A with shape (3, 3). Slice this array to get all columns except the last one, but reverse the order of the rows.

In [ ]:
# code
A = np.arange(1,10).reshape((3,3))
result = A[::-1, :-1]
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8]
 [4 5]
 [1 2]]


2. You have a 1D array A. Extract the elements that are multiples of 3 and also less than 7.

In [ ]:
# code
A = np.arange(1,10)
result = A[(A%3==0) & (A<7)]
print(result)

[1 2 3 4 5 6 7 8 9]
[3 6]


3. You have a 3D array A with shape (4, 3, 2). Swap the first and third axes and then reshape it into a 2D array.

In [ ]:
# code
A = np.arange(1, 25).reshape((4,3,2))
result = A.transpose(2, 1, 0).reshape((4,6))

# Does not matter
# result = A.transpose(2, 1, 0).reshape((4,-1))
# result = A.transpose(2, 1, 0).reshape((-1,8))
# result = A.transpose(2, 1, 0).reshape((8,3))
print(result)

[[ 1  7 13 19  3  9]
 [15 21  5 11 17 23]
 [ 2  8 14 20  4 10]
 [16 22  6 12 18 24]]


4. You have a 1D array A. Count the number of positive and negative elements in it.

In [ ]:
# code
A = np.array([-1, 2, 4, 5, -10])
pos = len(A[A>0])
neg = len(A[A<0])

# Does not matter
# pos = np.sum(A>0)
# neg = np.sum(A<0)

print(pos, neg)

3 2


5. You have a 3D array A with shape (5, 4, 7). Your task is to extract a **3D** slice from this array that includes:

* All elements from the last 2 planes in the third dimension,
* Elements from alternating indices along the first dimension.
* Elements from alternating indices along the second dimension, starting with the first element.

In [ ]:
# code
import numpy as np
A = np.arange(0, 140).reshape((5,4,7))
result = A[::2, 1::2, -2:]
print(result)

[[[  0   1   2   3   4   5   6]
  [  7   8   9  10  11  12  13]
  [ 14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27]]

 [[ 28  29  30  31  32  33  34]
  [ 35  36  37  38  39  40  41]
  [ 42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62]
  [ 63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76]
  [ 77  78  79  80  81  82  83]]

 [[ 84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97]
  [ 98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118]
  [119 120 121 122 123 124 125]
  [126 127 128 129 130 131 132]
  [133 134 135 136 137 138 139]]]
[[[ 12  13]
  [ 26  27]]

 [[ 68  69]
  [ 82  83]]

 [[124 125]
  [138 139]]]
